apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 32080
    nodePort: 32080
    targetPort: nginx-port
    #targetPort: redis-app-port
    name: nginx-svc-port
  selector:
    app: nginx-label
  type: NodePort