apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch-app-dep-node-selector
  labels:
    apps: scratch-app-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scratch-app-label
  template:
    metadata:
      name: scratch-app
      labels:
        app: scratch-app-label
    spec:
      containers:
      - name: k8s-demo
        image: ideepesh/k8s-demo
        ports:
        - name: deploy-port
          containerPort: 7080
      nodeSelector:
        hardware: commodity