apiVersion: v1
kind: Service
metadata:
  name: scratch-app-dep-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    protocol: TCP
    targetPort: deploy-port
  selector:
    app: scratch-app-label
  type: NodePort
