apiVersion: v1
kind: Pod
metadata:
  name: scratch-app
  labels:
    app: scratch-app-label
spec:
  containers:
  - name: k8s-demo
    image: ideepesh/k8s-demo
    ports:
    - name: one-pod-port
      containerPort: 7080