apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 32002
    nodePort: 32002
    targetPort: redis-port
    name: redis-svc-port
  selector:
    app: redis-pod-label
  type: NodePort
