apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod-label
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - name: redis-port
      containerPort: 6379